### ISSUE TITLE
Use virtual machines to replace glcoud instance

### ISSUE THREAD

**Issue by Mrx-yang** [OpenFogStack/celestial#10]
Hello, I plan to run this on my local computer(win 10) followed by the quick-start Tutorial, and I start three virtual machines to replace the three gcloud instances which you used in the quick-start tutorial, and the ip address of the three VMs are as follows:
![image](https://github.com/OpenFogStack/celestial/assets/57293284/d4f0030b-1adf-4326-836b-8b0e7cc70ace)
But I don't know to choose which configuration file to provision the ip address and port to let the two hosts and the cordinator can communicate with each other. I only find this file "validator.toml" (the path is ~/quick-start/validator/) has something about IP and port, It is originally like this:
![image](https://github.com/OpenFogStack/celestial/assets/57293284/771e63d1-209e-4ef6-9c01-5f4651c64871) 
And I try to change it according to the IP about my VMs like this:
![image](https://github.com/OpenFogStack/celestial/assets/57293284/55254188-8885-4b39-9a00-dba6bf146789)
But when I run the experiment, some mistakes occur:
![image](https://github.com/OpenFogStack/celestial/assets/57293284/8a5cd138-1d51-4789-8d88-351f5945c975)
![image](https://github.com/OpenFogStack/celestial/assets/57293284/7836a374-e3e5-412e-9be9-0f48716836b5)
And I really don't know how to solve it....
The environment configuration is quit exhausting.....

**Comment by ouzu** [comment]
Hello,

Firstly, a small disclaimer: I haven't worked with Celestial running on multiple machines, so my insight might be limited. But I'd be happy to try and help!

From the screenshots you've shared, it looks like there's a connection refused error.
One thing to check: When you changed the peering port from 1970 to 3000, did you ensure to start the Celestial server listening on this port?

Have you already ruled out any potential network and firewall configuration problems on your virtual machines?

Additionally, if you're running all the VMs on the same local machine, there might not be an advantage in setting up multiple VMs. It could simplify your setup by just running one Celestial server and client in a single VM. This might make configuration and troubleshooting more straightforward.

I hope this helps!

**Comment by pfandzelter** [comment]
Hi, the above comment is completely right (thank you for taking a look at this, @ouzu!).
@Mrx-yang you have made the correct changes to the configuration file (and there are no other configuration files to change), but please change the peering ports from `3000` back to `1970`. This should resolve the issue and let you move forward.
Thanks!
