### ISSUE TITLE
don't know how to configure

### ISSUE THREAD

**Issue by ykxian** [OpenFogStack/celestial#11]
Hello,
I am sorry to disturb you. I really don't know how to solve the problem.
I use 3 real workstations(pc6,pc7,pc8) to replace glcoud instance.
The IP addresses of them are as follows:
pc6:coordinator 192.168.3.46  192.168.1.100(wg0)
pc7:host 192.168.3.47  192.168.1.101(wg0)
pc8: host 192.168.3.49  192.168.1.102(wg0)
pc 6 is the server of wireguard.

Here is my configuration of wireguard:
validator.toml
```
hosts = ["192.168.1.101:1969", "192.168.1.101:1969"]
peeringhosts = ["192.168.1.101:1970", "192.168.1.102:1970"]
database = true
dbhost = "192.168.1.100:8000"
```
wg0.conf of pc6
```
[Interface]
Address = 192.168.1.100/24
SaveConfig = true
PostUp = iptables -A FORWARD -i %i -j ACCEPT; iptables -t nat -A POSTROUTING -o wlx0013ef803a83 -j MASQUERADE
PostDown = iptables -D FORWARD -i %i -j ACCEPT; iptables -t nat -D POSTROUTING -o wlx0013ef803a83 -j MASQUERADE
ListenPort = 51820
PrivateKey = +G90vAXLCxQPgQlztreDwYGx8I6euVqB+M1t8sWRSH0=

[Peer]
PublicKey = ANFf3/XR89V61jnPwFvTUchr7JU6A2LIylWObFzLkSQ=
AllowedIPs = 192.168.1.101/32
Endpoint = 192.168.3.47:54716

[Peer]
PublicKey = 8T2f+keUATDvRF13li+Z1RdwsvX1HTF1W8x55YLpFFA=
AllowedIPs = 192.168.1.102/32
Endpoint = 192.168.3.49:55827
```
wg0.conf of pc7
```
[Interface]
PrivateKey = ELIf5JAgS3IrPybkvVbmLucDvoR+jV3f1cEqAh6vN0Q= 
Address = 192.168.1.101/24

[Peer]
PublicKey = XEVoe214Rye0DfeimTKX75+60ixhPeCWe2XQmrSFaCU=  
Endpoint = 192.168.3.46:51820
AllowedIPs = 192.168.1.0/24
```
wg0.conf of pc8
```
[Interface]
PrivateKey = qE0sZIQL80ohjQ4gZ/mBWO7mQAXffhkPD6SdWalWEG0= 
Address = 192.168.1.102/24

[Peer]
PublicKey = XEVoe214Rye0DfeimTKX75+60ixhPeCWe2XQmrSFaCU=  
Endpoint = 192.168.3.46:51820
AllowedIPs = 192.168.1.0/24                
```
It works.I can ping pc7,pc8 from pc6.
![image](https://github.com/OpenFogStack/celestial/assets/150787122/3e2c4a30-d14b-4017-87a8-e8f7f393b1ff)

When I start the experiment, there is something wrong.
![image](https://github.com/OpenFogStack/celestial/assets/150787122/e11f6486-f1df-44ca-b694-17fc1d0e258c)

Could you give me some advice?

**Comment by pfandzelter** [comment]
Hi @ykxian, sorry for the delay in my answer! I'm not sure if you were able to solve this yourself already, but in short I believe the easiest option for you is to remove the wireguard configuration on your machines, as it might interfere with the wireguard configuration of Celestial (which Celestial automatically configures for you). If the machines are all on the same network (which they appear to be given their IP addresses), then simply enter the IPs into your configuration file:

```toml
hosts = ["192.168.3.47:1969", "192.168.3.49:1969"]
peeringhosts = ["192.168.3.47:1970", "192.168.3.49:1970"]
database = true
dbhost = "192.168.3.46:8000"
```

**Comment by ykxian** [comment]
Thanks for your reply @pfandzelter!
Now I start the experiment as you say.
```
hosts = ["192.168.3.47:1969", "192.168.3.49:1969"]
peeringhosts = ["192.168.3.47:1970", "192.168.3.49:1970"]
database = true
dbhost = "192.168.3.46:8000"
```
But it seems that there are still problems in generating keys...
 
![image](https://github.com/OpenFogStack/celestial/assets/150787122/f1b6e19e-0bde-4384-8096-587ca1af1d12)
Sorry to bother you again.

**Comment by pfandzelter** [comment]
It seems that wireguard is not configuring the keys correctly. Could you please share a screenshot of the output of one of the hosts and the contents of the `/celestial` directory on the host?

**Comment by ykxian** [comment]
host pc7:
![image](https://github.com/OpenFogStack/celestial/assets/150787122/eab42c33-aa54-4128-9113-01aa3b1bfade)
![image](https://github.com/OpenFogStack/celestial/assets/150787122/fece5ea6-4691-4782-a6b4-8cc32756c08b)
Thank you for your assistance.

**Comment by pfandzelter** [comment]
Turns out there was a bug in handling errors coming out of the Wireguard key generation (which is the likely culprit of your error). Please try again with the latest revision from the main branch. We should then at least see a different error

**Comment by ykxian** [comment]
OK, I will try it again. Thank you.

**Comment by ykxian** [comment]
`log.SetLevel(log.DebugLevel)`
![image](https://github.com/OpenFogStack/celestial/assets/150787122/2dde3424-f6bb-41bf-929e-7f209b385a59)
![image](https://github.com/OpenFogStack/celestial/assets/150787122/d7eb17e7-70a5-4492-bfff-c125543a29db)

**Comment by pfandzelter** [comment]
Ok, now I see the error. Please move your `~/celestial` folder to the root of your drive: `/celestial`:
```sh
sudo mv ~/celestial /celestial
```
Should do the trick. Currently the paths are hardcoded, although this is something I'm working on at the moment

**Comment by ykxian** [comment]
![image](https://github.com/OpenFogStack/celestial/assets/150787122/11cb56ee-ef04-4803-873c-7e1e9edf1a3e)

Thank you very much! It's running fine now.

**Comment by pfandzelter** [comment]
Sure, let me know if anything else comes up!
