### ISSUE TITLE
Problems in experiment

### ISSUE THREAD

**Issue by ykxian** [OpenFogStack/celestial#12]
I'm back to trouble you once more.
I encountered some problems when I started the experiment. The problems might be associated with iptables.
![image](https://github.com/OpenFogStack/celestial/assets/150787122/73477245-b237-4f8b-866f-8a03a9abcffe)
![image](https://github.com/OpenFogStack/celestial/assets/150787122/0dd83dd3-01a6-40bf-9856-bf02618b550e)
![image](https://github.com/OpenFogStack/celestial/assets/150787122/7d79d3d2-e8a0-4104-b6d7-4140eb1b01ec)
![image](https://github.com/OpenFogStack/celestial/assets/150787122/110885fa-a32f-4093-ad82-09002bf969b9)
![image](https://github.com/OpenFogStack/celestial/assets/150787122/a5e008c7-33c0-4002-b81f-33d087b2059c)
The experiment ran for 15 minutes, and there were undoubtedly issues with the results.
![image](https://github.com/OpenFogStack/celestial/assets/150787122/7435bc35-a526-4468-9e5f-9f68ecc5c69e)
Thanks for your help.

**Comment by pfandzelter** [comment]
Hi, I have actually seen this issue before, but I have never been able to replicate it. Please try the version of Celestial in the `tp/iptables-race-condition` branch, which should patch this issue. Unfortunately I can't merge this into `main` until I have found the underlying root cause. Thanks!

**Comment by ykxian** [comment]
Thanks! I will try again following your advice.

**Comment by ykxian** [comment]
It seems there are still some problems.
![image](https://github.com/OpenFogStack/celestial/assets/150787122/150b061f-773f-41de-bb9b-00272dab709b)
![image](https://github.com/OpenFogStack/celestial/assets/150787122/91d03853-fa15-4306-bc02-01a17c92692d)
![image](https://github.com/OpenFogStack/celestial/assets/150787122/3dc6c9d6-44eb-4b46-a084-585da0d532f7)

**Comment by pfandzelter** [comment]
Those errors can be ignored, it is a result of the default validation script (running on the emulated ground station) trying to figure out which satellites are active. It seems that other than that, everything is working fine

**Comment by ykxian** [comment]
But there still problems with the result analysis.
![image](https://github.com/OpenFogStack/celestial/assets/150787122/a00972a2-f68c-4d19-90b0-4e0db4579a93)

**Comment by pfandzelter** [comment]
It seems that only a few measurements are impacted, with a few connections being blocked that shouldn't be (or the other way around). With the current version of Celestial, this is the best we can get unfortunately because the underlying network emulation is slow and error-prone.
