### ISSUE TITLE
 A problem about routing

### ISSUE THREAD

**Issue by ykxian** [OpenFogStack/celestial#31]
Hi @pfandzelter , I noticed that the platform can query the shortest path between nodes, and the ping results indicate that the latency seems to match the calculated path delay. 
![image](https://github.com/OpenFogStack/celestial/assets/150787122/21b3fc7c-1931-48ae-ad57-5380fef2c237)
However, after checking the code, it seems there is no routing implementation for this part, only inter-host routing.
![image](https://github.com/OpenFogStack/celestial/assets/150787122/624c3a6d-7c55-42b7-9d69-aa225f467bd5)
How is the routing in Celestial implemented?

Thank you!

**Comment by pfandzelter** [comment]
Hi @ykxian, you can find the core of the update logic starting in [`pkg/orchestrator/orchestrator.go:208`](https://github.com/OpenFogStack/celestial/blob/7a46b06a1d0748c1e75be44cf005723a5421c94d/pkg/orchestrator/orchestrator.go#L208). There are methods for `BlockLink`, `UnblockLink`, `SetLatency`, and `SetBandwidth`, all pertaining to a link between to nodes (i.e., satellites). If you follow this through `pkg/orchestrator/virt.go` and `pkg/virt`, you will end up in our emulation backend, which currently is in `pkg/ebpfem`. Here the methods are implemented using our eBPF-based network emulation. Hope that helps!

**Comment by ykxian** [comment]
Hi @pfandzelter , thanks for your reply!
What I meant to ask is whether the data is forwarded along the shortest path when using ping.  It seems like the next-hop matrix isn't being used.

![image](https://github.com/OpenFogStack/celestial/assets/150787122/8396fa0d-a4b5-4694-8e5d-0338c27b3357)

These four methods are just for adjusting link connectivity, bandwidth, and latency, right?
`BlockLink`, `UnblockLink`, `SetLatency`, and `SetBandwidth`

**Comment by pfandzelter** [comment]
That's right, the matrix is only used during queries to the info API. The normal routing uses simply the IP forwarding capabilities of the host. There is no further routing, every to microVMs connect directly to each other.

**Comment by ykxian** [comment]
Okay, I understand. Thank you！
