### ISSUE TITLE
Run locally?

### ISSUE THREAD

**Issue by lucasa** [OpenFogStack/celestial#7]
Hi, congratulations for the nice project!

How can I run this locally or at my own remote server?

Thanks
Lucas

**Comment by pfandzelter** [comment]
Hi, thanks! You should be able to run this on an Ubuntu 20.04 server yourself (nested virtualization enabled if using a VM, check your hypervisor documentation for that). Follow the quick start but replace the `gcloud ssh` commands with normal `ssh` to your server. And make sure to provision your server as shown in the gcloud instance terraform
