### ISSUE TITLE
Simulating communication channel

### ISSUE THREAD

**Issue by zbh888** [OpenFogStack/celestial#8]
Hello OpenFogStack team,

I am going through the paper and I noticed you have a simulation of UE to LEO satellite communication link and an inter LEO satellite link. For my project, I need a simulator to simulate these two communication channels to exchange some RRC messages but I cannot find any....

Do you think it is possible to use some part of this project to simulate the two communication channels?

Thank you in advance!

**Comment by pfandzelter** [comment]
Hi, thanks for reaching out! The focus in our project is more on the computing side and the networking may not be as realistic as you need it to be. I'd recommend checking out [Hypatia](https://dl.acm.org/doi/abs/10.1145/3419394.3423635) and the related [satellite-ns3](https://satellite-ns3.com/)
